// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package paidinvoices

import "encoding/json"
import "fmt"
import "github.com/atombender/go-jsonschema/pkg/types"
import "regexp"

// Which invoices have been paid, and when. Payment is mutable state and
// deliberately lives outside the invoice documents, which are write-once once
// issued — see ARCHITECTURE.md §3.7. An object per payment rather than a bare
// number->date map, so a bank reference can be attached later without a schema
// break.
type PaidInvoicesJson struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema *string `json:"$schema,omitempty,omitzero" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// Paid corresponds to the JSON schema field "paid".
	Paid []Payment `json:"paid" yaml:"paid" mapstructure:"paid"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PaidInvoicesJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["paid"]; raw != nil && !ok {
		return fmt.Errorf("field paid in PaidInvoicesJson: required")
	}
	type Plain PaidInvoicesJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PaidInvoicesJson(plain)
	return nil
}

type Payment struct {
	// Date corresponds to the JSON schema field "date".
	Date types.SerializableDate `json:"date" yaml:"date" mapstructure:"date"`

	// Invoice corresponds to the JSON schema field "invoice".
	Invoice string `json:"invoice" yaml:"invoice" mapstructure:"invoice"`

	// Note corresponds to the JSON schema field "note".
	Note *string `json:"note,omitempty,omitzero" yaml:"note,omitempty" mapstructure:"note,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Payment) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["date"]; raw != nil && !ok {
		return fmt.Errorf("field date in Payment: required")
	}
	if _, ok := raw["invoice"]; raw != nil && !ok {
		return fmt.Errorf("field invoice in Payment: required")
	}
	type Plain Payment
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^INV-\d{10}$`, string(plain.Invoice)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Invoice", `^INV-\d{10}$`)
	}
	*j = Payment(plain)
	return nil
}
