// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package invoice

import "encoding/json"
import "fmt"
import "github.com/atombender/go-jsonschema/pkg/types"
import "reflect"
import "regexp"
import "unicode/utf8"

type Address struct {
	// City corresponds to the JSON schema field "city".
	City string `json:"city" yaml:"city" mapstructure:"city"`

	// CountryCode corresponds to the JSON schema field "country_code".
	CountryCode string `json:"country_code" yaml:"country_code" mapstructure:"country_code"`

	// Line1 corresponds to the JSON schema field "line1".
	Line1 string `json:"line1" yaml:"line1" mapstructure:"line1"`

	// Line2 corresponds to the JSON schema field "line2".
	Line2 *string `json:"line2,omitempty,omitzero" yaml:"line2,omitempty" mapstructure:"line2,omitempty"`

	// PostalCode corresponds to the JSON schema field "postal_code".
	PostalCode string `json:"postal_code" yaml:"postal_code" mapstructure:"postal_code"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Address) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["city"]; raw != nil && !ok {
		return fmt.Errorf("field city in Address: required")
	}
	if _, ok := raw["country_code"]; raw != nil && !ok {
		return fmt.Errorf("field country_code in Address: required")
	}
	if _, ok := raw["line1"]; raw != nil && !ok {
		return fmt.Errorf("field line1 in Address: required")
	}
	if _, ok := raw["postal_code"]; raw != nil && !ok {
		return fmt.Errorf("field postal_code in Address: required")
	}
	type Plain Address
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.City)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "city", 1)
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{2}$`, string(plain.CountryCode)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "CountryCode", `^[A-Z]{2}$`)
	}
	if utf8.RuneCountInString(string(plain.Line1)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "line1", 1)
	}
	if utf8.RuneCountInString(string(plain.PostalCode)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "postal_code", 1)
	}
	*j = Address(plain)
	return nil
}

type Bank struct {
	// Bic corresponds to the JSON schema field "bic".
	Bic string `json:"bic" yaml:"bic" mapstructure:"bic"`

	// Iban corresponds to the JSON schema field "iban".
	Iban string `json:"iban" yaml:"iban" mapstructure:"iban"`

	// IntermediaryBic corresponds to the JSON schema field "intermediary_bic".
	IntermediaryBic *string `json:"intermediary_bic,omitempty,omitzero" yaml:"intermediary_bic,omitempty" mapstructure:"intermediary_bic,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Bank) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bic"]; raw != nil && !ok {
		return fmt.Errorf("field bic in Bank: required")
	}
	if _, ok := raw["iban"]; raw != nil && !ok {
		return fmt.Errorf("field iban in Bank: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Bank: required")
	}
	type Plain Bank
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Bic)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "bic", 1)
	}
	if utf8.RuneCountInString(string(plain.Iban)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "iban", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = Bank(plain)
	return nil
}

type Discount struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount *int `json:"amount,omitempty,omitzero" yaml:"amount,omitempty" mapstructure:"amount,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label LocalizedString `json:"label" yaml:"label" mapstructure:"label"`

	// Percent corresponds to the JSON schema field "percent".
	Percent *int `json:"percent,omitempty,omitzero" yaml:"percent,omitempty" mapstructure:"percent,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Discount) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in Discount: required")
	}
	type Plain Discount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Percent != nil && 0 > *plain.Percent {
		return fmt.Errorf("field %s: must be >= %v", "percent", 0)
	}
	*j = Discount(plain)
	return nil
}

type InvoiceJson struct {
	// Currency corresponds to the JSON schema field "currency".
	Currency string `json:"currency" yaml:"currency" mapstructure:"currency"`

	// Discounts corresponds to the JSON schema field "discounts".
	Discounts []Discount `json:"discounts,omitempty,omitzero" yaml:"discounts,omitempty" mapstructure:"discounts,omitempty"`

	// DueDate corresponds to the JSON schema field "due_date".
	DueDate types.SerializableDate `json:"due_date" yaml:"due_date" mapstructure:"due_date"`

	// IssueDate corresponds to the JSON schema field "issue_date".
	IssueDate types.SerializableDate `json:"issue_date" yaml:"issue_date" mapstructure:"issue_date"`

	// Issuer corresponds to the JSON schema field "issuer".
	Issuer IssuerSnapshot `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Language corresponds to the JSON schema field "language".
	Language InvoiceJsonLanguage `json:"language" yaml:"language" mapstructure:"language"`

	// Lines corresponds to the JSON schema field "lines".
	Lines []Line `json:"lines" yaml:"lines" mapstructure:"lines"`

	// Number corresponds to the JSON schema field "number".
	Number string `json:"number" yaml:"number" mapstructure:"number"`

	// Recipient corresponds to the JSON schema field "recipient".
	Recipient RecipientSnapshot `json:"recipient" yaml:"recipient" mapstructure:"recipient"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion interface{} `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// Status corresponds to the JSON schema field "status".
	Status InvoiceJsonStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Tax corresponds to the JSON schema field "tax".
	Tax Tax `json:"tax" yaml:"tax" mapstructure:"tax"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type InvoiceJsonLanguage string

const InvoiceJsonLanguageBg InvoiceJsonLanguage = "bg"
const InvoiceJsonLanguageDe InvoiceJsonLanguage = "de"
const InvoiceJsonLanguageEn InvoiceJsonLanguage = "en"
const InvoiceJsonLanguageFr InvoiceJsonLanguage = "fr"

var enumValues_InvoiceJsonLanguage = []interface{}{
	"de",
	"en",
	"fr",
	"bg",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvoiceJsonLanguage) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InvoiceJsonLanguage {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InvoiceJsonLanguage, v)
	}
	*j = InvoiceJsonLanguage(v)
	return nil
}

type InvoiceJsonStatus string

const InvoiceJsonStatusDraft InvoiceJsonStatus = "draft"
const InvoiceJsonStatusIssued InvoiceJsonStatus = "issued"

var enumValues_InvoiceJsonStatus = []interface{}{
	"draft",
	"issued",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvoiceJsonStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InvoiceJsonStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InvoiceJsonStatus, v)
	}
	*j = InvoiceJsonStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvoiceJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["currency"]; raw != nil && !ok {
		return fmt.Errorf("field currency in InvoiceJson: required")
	}
	if _, ok := raw["due_date"]; raw != nil && !ok {
		return fmt.Errorf("field due_date in InvoiceJson: required")
	}
	if _, ok := raw["issue_date"]; raw != nil && !ok {
		return fmt.Errorf("field issue_date in InvoiceJson: required")
	}
	if _, ok := raw["issuer"]; raw != nil && !ok {
		return fmt.Errorf("field issuer in InvoiceJson: required")
	}
	if _, ok := raw["language"]; raw != nil && !ok {
		return fmt.Errorf("field language in InvoiceJson: required")
	}
	if _, ok := raw["lines"]; raw != nil && !ok {
		return fmt.Errorf("field lines in InvoiceJson: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in InvoiceJson: required")
	}
	if _, ok := raw["recipient"]; raw != nil && !ok {
		return fmt.Errorf("field recipient in InvoiceJson: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in InvoiceJson: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in InvoiceJson: required")
	}
	if _, ok := raw["tax"]; raw != nil && !ok {
		return fmt.Errorf("field tax in InvoiceJson: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in InvoiceJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in InvoiceJson: required")
	}
	type Plain InvoiceJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{3}$`, string(plain.Currency)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Currency", `^[A-Z]{3}$`)
	}
	if plain.Lines != nil && len(plain.Lines) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "lines", 1)
	}
	if matched, _ := regexp.MatchString(`^INV-\d{10}$`, string(plain.Number)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Number", `^INV-\d{10}$`)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	if plain.Type != "invoice" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "invoice")
	}
	*j = InvoiceJson(plain)
	return nil
}

type IssuerSnapshot struct {
	// Address corresponds to the JSON schema field "address".
	Address Address `json:"address" yaml:"address" mapstructure:"address"`

	// Bank corresponds to the JSON schema field "bank".
	Bank Bank `json:"bank" yaml:"bank" mapstructure:"bank"`

	// DefaultCurrency corresponds to the JSON schema field "default_currency".
	DefaultCurrency string `json:"default_currency" yaml:"default_currency" mapstructure:"default_currency"`

	// LegalName corresponds to the JSON schema field "legal_name".
	LegalName string `json:"legal_name" yaml:"legal_name" mapstructure:"legal_name"`

	// Logo corresponds to the JSON schema field "logo".
	Logo *string `json:"logo,omitempty,omitzero" yaml:"logo,omitempty" mapstructure:"logo,omitempty"`

	// TaxId corresponds to the JSON schema field "tax_id".
	TaxId string `json:"tax_id" yaml:"tax_id" mapstructure:"tax_id"`

	// VatId corresponds to the JSON schema field "vat_id".
	VatId string `json:"vat_id" yaml:"vat_id" mapstructure:"vat_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IssuerSnapshot) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["address"]; raw != nil && !ok {
		return fmt.Errorf("field address in IssuerSnapshot: required")
	}
	if _, ok := raw["bank"]; raw != nil && !ok {
		return fmt.Errorf("field bank in IssuerSnapshot: required")
	}
	if _, ok := raw["default_currency"]; raw != nil && !ok {
		return fmt.Errorf("field default_currency in IssuerSnapshot: required")
	}
	if _, ok := raw["legal_name"]; raw != nil && !ok {
		return fmt.Errorf("field legal_name in IssuerSnapshot: required")
	}
	if _, ok := raw["tax_id"]; raw != nil && !ok {
		return fmt.Errorf("field tax_id in IssuerSnapshot: required")
	}
	if _, ok := raw["vat_id"]; raw != nil && !ok {
		return fmt.Errorf("field vat_id in IssuerSnapshot: required")
	}
	type Plain IssuerSnapshot
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{3}$`, string(plain.DefaultCurrency)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "DefaultCurrency", `^[A-Z]{3}$`)
	}
	if utf8.RuneCountInString(string(plain.LegalName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "legal_name", 1)
	}
	if utf8.RuneCountInString(string(plain.TaxId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "tax_id", 1)
	}
	if utf8.RuneCountInString(string(plain.VatId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "vat_id", 1)
	}
	*j = IssuerSnapshot(plain)
	return nil
}

type Line struct {
	// Description corresponds to the JSON schema field "description".
	Description LocalizedString `json:"description" yaml:"description" mapstructure:"description"`

	// Quantity corresponds to the JSON schema field "quantity".
	Quantity *int `json:"quantity,omitempty,omitzero" yaml:"quantity,omitempty" mapstructure:"quantity,omitempty"`

	// Unit corresponds to the JSON schema field "unit".
	Unit *string `json:"unit,omitempty,omitzero" yaml:"unit,omitempty" mapstructure:"unit,omitempty"`

	// UnitPrice corresponds to the JSON schema field "unit_price".
	UnitPrice int `json:"unit_price" yaml:"unit_price" mapstructure:"unit_price"`

	// VatRate corresponds to the JSON schema field "vat_rate".
	VatRate int `json:"vat_rate" yaml:"vat_rate" mapstructure:"vat_rate"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Line) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in Line: required")
	}
	if _, ok := raw["unit_price"]; raw != nil && !ok {
		return fmt.Errorf("field unit_price in Line: required")
	}
	if _, ok := raw["vat_rate"]; raw != nil && !ok {
		return fmt.Errorf("field vat_rate in Line: required")
	}
	type Plain Line
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Quantity != nil && 1 > *plain.Quantity {
		return fmt.Errorf("field %s: must be >= %v", "quantity", 1)
	}
	if 100 < plain.VatRate {
		return fmt.Errorf("field %s: must be <= %v", "vat_rate", 100)
	}
	if 0 > plain.VatRate {
		return fmt.Errorf("field %s: must be >= %v", "vat_rate", 0)
	}
	*j = Line(plain)
	return nil
}

type LocalizedString struct {
	// Bg corresponds to the JSON schema field "bg".
	Bg *string `json:"bg,omitempty,omitzero" yaml:"bg,omitempty" mapstructure:"bg,omitempty"`

	// De corresponds to the JSON schema field "de".
	De *string `json:"de,omitempty,omitzero" yaml:"de,omitempty" mapstructure:"de,omitempty"`

	// En corresponds to the JSON schema field "en".
	En *string `json:"en,omitempty,omitzero" yaml:"en,omitempty" mapstructure:"en,omitempty"`

	// Fr corresponds to the JSON schema field "fr".
	Fr *string `json:"fr,omitempty,omitzero" yaml:"fr,omitempty" mapstructure:"fr,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LocalizedString) UnmarshalJSON(value []byte) error {
	type Plain LocalizedString
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Bg != nil && utf8.RuneCountInString(string(*plain.Bg)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "bg", 1)
	}
	if plain.De != nil && utf8.RuneCountInString(string(*plain.De)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "de", 1)
	}
	if plain.En != nil && utf8.RuneCountInString(string(*plain.En)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "en", 1)
	}
	if plain.Fr != nil && utf8.RuneCountInString(string(*plain.Fr)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "fr", 1)
	}
	*j = LocalizedString(plain)
	return nil
}

type RecipientSnapshot struct {
	// Address corresponds to the JSON schema field "address".
	Address Address `json:"address" yaml:"address" mapstructure:"address"`

	// Email corresponds to the JSON schema field "email".
	Email string `json:"email" yaml:"email" mapstructure:"email"`

	// IsBusiness corresponds to the JSON schema field "is_business".
	IsBusiness bool `json:"is_business" yaml:"is_business" mapstructure:"is_business"`

	// Language corresponds to the JSON schema field "language".
	Language RecipientSnapshotLanguage `json:"language" yaml:"language" mapstructure:"language"`

	// LegalName corresponds to the JSON schema field "legal_name".
	LegalName string `json:"legal_name" yaml:"legal_name" mapstructure:"legal_name"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number" yaml:"number" mapstructure:"number"`

	// PaymentTermsDays corresponds to the JSON schema field "payment_terms_days".
	PaymentTermsDays int `json:"payment_terms_days" yaml:"payment_terms_days" mapstructure:"payment_terms_days"`

	// TaxId corresponds to the JSON schema field "tax_id".
	TaxId *string `json:"tax_id,omitempty,omitzero" yaml:"tax_id,omitempty" mapstructure:"tax_id,omitempty"`

	// VatId corresponds to the JSON schema field "vat_id".
	VatId *string `json:"vat_id,omitempty,omitzero" yaml:"vat_id,omitempty" mapstructure:"vat_id,omitempty"`
}

type RecipientSnapshotLanguage string

const RecipientSnapshotLanguageBg RecipientSnapshotLanguage = "bg"
const RecipientSnapshotLanguageDe RecipientSnapshotLanguage = "de"
const RecipientSnapshotLanguageEn RecipientSnapshotLanguage = "en"
const RecipientSnapshotLanguageFr RecipientSnapshotLanguage = "fr"

var enumValues_RecipientSnapshotLanguage = []interface{}{
	"de",
	"en",
	"fr",
	"bg",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RecipientSnapshotLanguage) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RecipientSnapshotLanguage {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RecipientSnapshotLanguage, v)
	}
	*j = RecipientSnapshotLanguage(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RecipientSnapshot) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["address"]; raw != nil && !ok {
		return fmt.Errorf("field address in RecipientSnapshot: required")
	}
	if _, ok := raw["email"]; raw != nil && !ok {
		return fmt.Errorf("field email in RecipientSnapshot: required")
	}
	if _, ok := raw["is_business"]; raw != nil && !ok {
		return fmt.Errorf("field is_business in RecipientSnapshot: required")
	}
	if _, ok := raw["language"]; raw != nil && !ok {
		return fmt.Errorf("field language in RecipientSnapshot: required")
	}
	if _, ok := raw["legal_name"]; raw != nil && !ok {
		return fmt.Errorf("field legal_name in RecipientSnapshot: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in RecipientSnapshot: required")
	}
	if _, ok := raw["payment_terms_days"]; raw != nil && !ok {
		return fmt.Errorf("field payment_terms_days in RecipientSnapshot: required")
	}
	type Plain RecipientSnapshot
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.LegalName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "legal_name", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if 0 > plain.PaymentTermsDays {
		return fmt.Errorf("field %s: must be >= %v", "payment_terms_days", 0)
	}
	*j = RecipientSnapshot(plain)
	return nil
}

type Tax struct {
	// Citations corresponds to the JSON schema field "citations".
	Citations []string `json:"citations" yaml:"citations" mapstructure:"citations"`

	// Note corresponds to the JSON schema field "note".
	Note LocalizedString `json:"note" yaml:"note" mapstructure:"note"`

	// Regime corresponds to the JSON schema field "regime".
	Regime TaxRegime `json:"regime" yaml:"regime" mapstructure:"regime"`
}

type TaxRegime string

const TaxRegimeDomesticStandard TaxRegime = "domestic_standard"
const TaxRegimeEuB2BReverseCharge TaxRegime = "eu_b2b_reverse_charge"
const TaxRegimeOutsideEuPlaceOfSupply TaxRegime = "outside_eu_place_of_supply"

var enumValues_TaxRegime = []interface{}{
	"domestic_standard",
	"eu_b2b_reverse_charge",
	"outside_eu_place_of_supply",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaxRegime) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaxRegime {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaxRegime, v)
	}
	*j = TaxRegime(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Tax) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["citations"]; raw != nil && !ok {
		return fmt.Errorf("field citations in Tax: required")
	}
	if _, ok := raw["note"]; raw != nil && !ok {
		return fmt.Errorf("field note in Tax: required")
	}
	if _, ok := raw["regime"]; raw != nil && !ok {
		return fmt.Errorf("field regime in Tax: required")
	}
	type Plain Tax
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Tax(plain)
	return nil
}
