// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package actualsdata

import "encoding/json"
import "fmt"
import "regexp"
import "unicode/utf8"

// What was ACTUALLY spent in one month, reconciled from bank statements — one file
// per month, named for the month it covers (data/actuals/2026-08.json). Display
// only: nothing here feeds Balance, Available to spend, Total private expenses or
// the account roll-forward, all of which stay planned-based. Every transaction
// carries exactly one of category or ignored, so the file accounts for every row
// on the statement and 'deliberately skipped' is recorded rather than inferred
// from absence. coverage is what stops a mid-month import reading as a spectacular
// underspend.
type ActualsFile struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema *string `json:"$schema,omitempty,omitzero" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// Which account was read, and through which dates. Never empty: 'nothing imported
	// yet' is the absent file, not an empty one. Until coverage spans the whole month
	// the dashboard withholds any under-budget judgement, since on the 5th every
	// category is trivially under.
	Coverage []Coverage `json:"coverage" yaml:"coverage" mapstructure:"coverage"`

	// The month this file covers, YYYY-MM. Must match the filename — a mismatch means
	// an import was saved over the wrong month.
	Month string `json:"month" yaml:"month" mapstructure:"month"`

	// Transactions corresponds to the JSON schema field "transactions".
	Transactions []Transaction `json:"transactions" yaml:"transactions" mapstructure:"transactions"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActualsFile) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["coverage"]; raw != nil && !ok {
		return fmt.Errorf("field coverage in ActualsFile: required")
	}
	if _, ok := raw["month"]; raw != nil && !ok {
		return fmt.Errorf("field month in ActualsFile: required")
	}
	if _, ok := raw["transactions"]; raw != nil && !ok {
		return fmt.Errorf("field transactions in ActualsFile: required")
	}
	type Plain ActualsFile
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Coverage != nil && len(plain.Coverage) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "coverage", 1)
	}
	if matched, _ := regexp.MatchString(`^[0-9]{4}-(0[1-9]|1[0-2])$`, string(plain.Month)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Month", `^[0-9]{4}-(0[1-9]|1[0-2])$`)
	}
	*j = ActualsFile(plain)
	return nil
}

type Coverage struct {
	// The account this range was read from, spelled as the transactions spell it.
	Account string `json:"account" yaml:"account" mapstructure:"account"`

	// First day read, inclusive. Must fall inside month.
	From string `json:"from" yaml:"from" mapstructure:"from"`

	// When the statement was read. Informational — only from/to affect any figure.
	ImportedAt string `json:"imported_at" yaml:"imported_at" mapstructure:"imported_at"`

	// Last day read, inclusive. Must fall inside month and not precede from.
	To string `json:"to" yaml:"to" mapstructure:"to"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Coverage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["account"]; raw != nil && !ok {
		return fmt.Errorf("field account in Coverage: required")
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in Coverage: required")
	}
	if _, ok := raw["imported_at"]; raw != nil && !ok {
		return fmt.Errorf("field imported_at in Coverage: required")
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in Coverage: required")
	}
	type Plain Coverage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Account)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "account", 1)
	}
	if matched, _ := regexp.MatchString(`^[0-9]{4}-[0-9]{2}-[0-9]{2}$`, string(plain.From)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "From", `^[0-9]{4}-[0-9]{2}-[0-9]{2}$`)
	}
	if matched, _ := regexp.MatchString(`^[0-9]{4}-[0-9]{2}-[0-9]{2}$`, string(plain.ImportedAt)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ImportedAt", `^[0-9]{4}-[0-9]{2}-[0-9]{2}$`)
	}
	if matched, _ := regexp.MatchString(`^[0-9]{4}-[0-9]{2}-[0-9]{2}$`, string(plain.To)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "To", `^[0-9]{4}-[0-9]{2}-[0-9]{2}$`)
	}
	*j = Coverage(plain)
	return nil
}

type Transaction struct {
	// Which account it was charged to. Free text: accounts.json models private
	// accounts only, so a company card has nowhere to be declared.
	Account string `json:"account" yaml:"account" mapstructure:"account"`

	// Euros, decimals allowed. Positive = money out, matching budget.json's
	// convention; a refund is a negative amount against the same category. Never 0 —
	// a zero line is noise, and 'saw it, not an expense' is what ignored is for.
	Amount float64 `json:"amount" yaml:"amount" mapstructure:"amount"`

	// The budget category id this line belongs to. Exactly one of category or ignored
	// must be set — that rule is enforced in Go, since expressing it here would
	// generate poor code. A category that no longer resolves fails validation loudly
	// rather than silently dropping the money.
	Category *string `json:"category,omitempty,omitzero" yaml:"category,omitempty" mapstructure:"category,omitempty"`

	// Must fall inside month: a statement spanning a month boundary splits into two
	// files.
	Date string `json:"date" yaml:"date" mapstructure:"date"`

	// The statement line as the bank wrote it. Admin-only — it never reaches a
	// non-admin session's HTML, and only the spending detail page renders it.
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Stable within this file, so re-uploading the same statement is idempotent
	// rather than duplicating every line. Derived deterministically from
	// account+date+amount+description, with a -2 suffix on collision.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Why this line is not a budget expense — 'salary', 'transfer to savings'. A
	// non-empty reason, never a bare true: the file is meant to reconcile
	// line-for-line against the statement, and the spending page lists these so a
	// mis-ignored line is visible. Excluded from every figure.
	Ignored *string `json:"ignored,omitempty,omitzero" yaml:"ignored,omitempty" mapstructure:"ignored,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Transaction) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["account"]; raw != nil && !ok {
		return fmt.Errorf("field account in Transaction: required")
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in Transaction: required")
	}
	if _, ok := raw["date"]; raw != nil && !ok {
		return fmt.Errorf("field date in Transaction: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in Transaction: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Transaction: required")
	}
	type Plain Transaction
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Account)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "account", 1)
	}
	if matched, _ := regexp.MatchString(`^[0-9]{4}-[0-9]{2}-[0-9]{2}$`, string(plain.Date)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Date", `^[0-9]{4}-[0-9]{2}-[0-9]{2}$`)
	}
	if utf8.RuneCountInString(string(plain.Description)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "description", 1)
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if plain.Ignored != nil && utf8.RuneCountInString(string(*plain.Ignored)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "ignored", 1)
	}
	*j = Transaction(plain)
	return nil
}
