// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package issuer

import "encoding/json"
import "fmt"
import "regexp"
import "unicode/utf8"

type Address struct {
	// City corresponds to the JSON schema field "city".
	City string `json:"city" yaml:"city" mapstructure:"city"`

	// CountryCode corresponds to the JSON schema field "country_code".
	CountryCode string `json:"country_code" yaml:"country_code" mapstructure:"country_code"`

	// Line1 corresponds to the JSON schema field "line1".
	Line1 string `json:"line1" yaml:"line1" mapstructure:"line1"`

	// Line2 corresponds to the JSON schema field "line2".
	Line2 *string `json:"line2,omitempty,omitzero" yaml:"line2,omitempty" mapstructure:"line2,omitempty"`

	// PostalCode corresponds to the JSON schema field "postal_code".
	PostalCode string `json:"postal_code" yaml:"postal_code" mapstructure:"postal_code"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Address) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["city"]; raw != nil && !ok {
		return fmt.Errorf("field city in Address: required")
	}
	if _, ok := raw["country_code"]; raw != nil && !ok {
		return fmt.Errorf("field country_code in Address: required")
	}
	if _, ok := raw["line1"]; raw != nil && !ok {
		return fmt.Errorf("field line1 in Address: required")
	}
	if _, ok := raw["postal_code"]; raw != nil && !ok {
		return fmt.Errorf("field postal_code in Address: required")
	}
	type Plain Address
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.City)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "city", 1)
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{2}$`, string(plain.CountryCode)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "CountryCode", `^[A-Z]{2}$`)
	}
	if utf8.RuneCountInString(string(plain.Line1)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "line1", 1)
	}
	if utf8.RuneCountInString(string(plain.PostalCode)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "postal_code", 1)
	}
	*j = Address(plain)
	return nil
}

type Bank struct {
	// Bic corresponds to the JSON schema field "bic".
	Bic string `json:"bic" yaml:"bic" mapstructure:"bic"`

	// Iban corresponds to the JSON schema field "iban".
	Iban string `json:"iban" yaml:"iban" mapstructure:"iban"`

	// IntermediaryBic corresponds to the JSON schema field "intermediary_bic".
	IntermediaryBic *string `json:"intermediary_bic,omitempty,omitzero" yaml:"intermediary_bic,omitempty" mapstructure:"intermediary_bic,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Bank) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bic"]; raw != nil && !ok {
		return fmt.Errorf("field bic in Bank: required")
	}
	if _, ok := raw["iban"]; raw != nil && !ok {
		return fmt.Errorf("field iban in Bank: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Bank: required")
	}
	type Plain Bank
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Bic)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "bic", 1)
	}
	if utf8.RuneCountInString(string(plain.Iban)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "iban", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = Bank(plain)
	return nil
}

type IssuerJson struct {
	// Address corresponds to the JSON schema field "address".
	Address Address `json:"address" yaml:"address" mapstructure:"address"`

	// Bank corresponds to the JSON schema field "bank".
	Bank Bank `json:"bank" yaml:"bank" mapstructure:"bank"`

	// DefaultCurrency corresponds to the JSON schema field "default_currency".
	DefaultCurrency string `json:"default_currency" yaml:"default_currency" mapstructure:"default_currency"`

	// LegalName corresponds to the JSON schema field "legal_name".
	LegalName string `json:"legal_name" yaml:"legal_name" mapstructure:"legal_name"`

	// Logo corresponds to the JSON schema field "logo".
	Logo *string `json:"logo,omitempty,omitzero" yaml:"logo,omitempty" mapstructure:"logo,omitempty"`

	// TaxId corresponds to the JSON schema field "tax_id".
	TaxId string `json:"tax_id" yaml:"tax_id" mapstructure:"tax_id"`

	// VatId corresponds to the JSON schema field "vat_id".
	VatId string `json:"vat_id" yaml:"vat_id" mapstructure:"vat_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *IssuerJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["address"]; raw != nil && !ok {
		return fmt.Errorf("field address in IssuerJson: required")
	}
	if _, ok := raw["bank"]; raw != nil && !ok {
		return fmt.Errorf("field bank in IssuerJson: required")
	}
	if _, ok := raw["default_currency"]; raw != nil && !ok {
		return fmt.Errorf("field default_currency in IssuerJson: required")
	}
	if _, ok := raw["legal_name"]; raw != nil && !ok {
		return fmt.Errorf("field legal_name in IssuerJson: required")
	}
	if _, ok := raw["tax_id"]; raw != nil && !ok {
		return fmt.Errorf("field tax_id in IssuerJson: required")
	}
	if _, ok := raw["vat_id"]; raw != nil && !ok {
		return fmt.Errorf("field vat_id in IssuerJson: required")
	}
	type Plain IssuerJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{3}$`, string(plain.DefaultCurrency)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "DefaultCurrency", `^[A-Z]{3}$`)
	}
	if utf8.RuneCountInString(string(plain.LegalName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "legal_name", 1)
	}
	if utf8.RuneCountInString(string(plain.TaxId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "tax_id", 1)
	}
	if utf8.RuneCountInString(string(plain.VatId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "vat_id", 1)
	}
	*j = IssuerJson(plain)
	return nil
}
