// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package users

import "encoding/json"
import "fmt"
import "reflect"

type User struct {
	// Email corresponds to the JSON schema field "email".
	Email string `json:"email" yaml:"email" mapstructure:"email"`

	// Parts corresponds to the JSON schema field "parts".
	Parts []UserPartsElem `json:"parts" yaml:"parts" mapstructure:"parts"`
}

type UserPartsElem string

const UserPartsElemFinance UserPartsElem = "finance"
const UserPartsElemInvoicing UserPartsElem = "invoicing"

var enumValues_UserPartsElem = []interface{}{
	"finance",
	"invoicing",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserPartsElem) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UserPartsElem {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_UserPartsElem, v)
	}
	*j = UserPartsElem(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *User) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["email"]; raw != nil && !ok {
		return fmt.Errorf("field email in User: required")
	}
	if _, ok := raw["parts"]; raw != nil && !ok {
		return fmt.Errorf("field parts in User: required")
	}
	type Plain User
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Parts != nil && len(plain.Parts) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "parts", 1)
	}
	*j = User(plain)
	return nil
}

// Non-collaborator access control: which part(s) of PocketCFO an
// email-OTP-authenticated user may reach. GitHub repo collaborators are always
// full-access admins and are never listed here — see internal/auth and AGENTS.md.
type UsersJson struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema *string `json:"$schema,omitempty,omitzero" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// Users corresponds to the JSON schema field "users".
	Users []User `json:"users" yaml:"users" mapstructure:"users"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UsersJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["users"]; raw != nil && !ok {
		return fmt.Errorf("field users in UsersJson: required")
	}
	type Plain UsersJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UsersJson(plain)
	return nil
}
