// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package notes

import "encoding/json"
import "fmt"
import "github.com/atombender/go-jsonschema/pkg/types"
import "unicode/utf8"

type Entry struct {
	// Citations corresponds to the JSON schema field "citations".
	Citations []string `json:"citations" yaml:"citations" mapstructure:"citations"`

	// MandatoryWording corresponds to the JSON schema field "mandatory_wording".
	MandatoryWording []string `json:"mandatory_wording" yaml:"mandatory_wording" mapstructure:"mandatory_wording"`

	// ReviewedAt corresponds to the JSON schema field "reviewed_at".
	ReviewedAt types.SerializableDate `json:"reviewed_at" yaml:"reviewed_at" mapstructure:"reviewed_at"`

	// Text corresponds to the JSON schema field "text".
	Text LocalizedString `json:"text" yaml:"text" mapstructure:"text"`

	// ViesReportable corresponds to the JSON schema field "vies_reportable".
	ViesReportable bool `json:"vies_reportable" yaml:"vies_reportable" mapstructure:"vies_reportable"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Entry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["citations"]; raw != nil && !ok {
		return fmt.Errorf("field citations in Entry: required")
	}
	if _, ok := raw["mandatory_wording"]; raw != nil && !ok {
		return fmt.Errorf("field mandatory_wording in Entry: required")
	}
	if _, ok := raw["reviewed_at"]; raw != nil && !ok {
		return fmt.Errorf("field reviewed_at in Entry: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in Entry: required")
	}
	if _, ok := raw["vies_reportable"]; raw != nil && !ok {
		return fmt.Errorf("field vies_reportable in Entry: required")
	}
	type Plain Entry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Entry(plain)
	return nil
}

type LocalizedString struct {
	// Bg corresponds to the JSON schema field "bg".
	Bg *string `json:"bg,omitempty,omitzero" yaml:"bg,omitempty" mapstructure:"bg,omitempty"`

	// De corresponds to the JSON schema field "de".
	De *string `json:"de,omitempty,omitzero" yaml:"de,omitempty" mapstructure:"de,omitempty"`

	// En corresponds to the JSON schema field "en".
	En *string `json:"en,omitempty,omitzero" yaml:"en,omitempty" mapstructure:"en,omitempty"`

	// Fr corresponds to the JSON schema field "fr".
	Fr *string `json:"fr,omitempty,omitzero" yaml:"fr,omitempty" mapstructure:"fr,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LocalizedString) UnmarshalJSON(value []byte) error {
	type Plain LocalizedString
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Bg != nil && utf8.RuneCountInString(string(*plain.Bg)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "bg", 1)
	}
	if plain.De != nil && utf8.RuneCountInString(string(*plain.De)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "de", 1)
	}
	if plain.En != nil && utf8.RuneCountInString(string(*plain.En)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "en", 1)
	}
	if plain.Fr != nil && utf8.RuneCountInString(string(*plain.Fr)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "fr", 1)
	}
	*j = LocalizedString(plain)
	return nil
}

type NotesJson struct {
	// Regimes corresponds to the JSON schema field "regimes".
	Regimes NotesJsonRegimes `json:"regimes" yaml:"regimes" mapstructure:"regimes"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

type NotesJsonRegimes map[string]Entry

// UnmarshalJSON implements json.Unmarshaler.
func (j *NotesJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["regimes"]; raw != nil && !ok {
		return fmt.Errorf("field regimes in NotesJson: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in NotesJson: required")
	}
	type Plain NotesJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Version {
		return fmt.Errorf("field %s: must be >= %v", "version", 1)
	}
	*j = NotesJson(plain)
	return nil
}
