// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package recipient

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "unicode/utf8"

type Address struct {
	// City corresponds to the JSON schema field "city".
	City string `json:"city" yaml:"city" mapstructure:"city"`

	// CountryCode corresponds to the JSON schema field "country_code".
	CountryCode string `json:"country_code" yaml:"country_code" mapstructure:"country_code"`

	// Line1 corresponds to the JSON schema field "line1".
	Line1 string `json:"line1" yaml:"line1" mapstructure:"line1"`

	// Line2 corresponds to the JSON schema field "line2".
	Line2 *string `json:"line2,omitempty,omitzero" yaml:"line2,omitempty" mapstructure:"line2,omitempty"`

	// PostalCode corresponds to the JSON schema field "postal_code".
	PostalCode string `json:"postal_code" yaml:"postal_code" mapstructure:"postal_code"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Address) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["city"]; raw != nil && !ok {
		return fmt.Errorf("field city in Address: required")
	}
	if _, ok := raw["country_code"]; raw != nil && !ok {
		return fmt.Errorf("field country_code in Address: required")
	}
	if _, ok := raw["line1"]; raw != nil && !ok {
		return fmt.Errorf("field line1 in Address: required")
	}
	if _, ok := raw["postal_code"]; raw != nil && !ok {
		return fmt.Errorf("field postal_code in Address: required")
	}
	type Plain Address
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.City)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "city", 1)
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{2}$`, string(plain.CountryCode)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "CountryCode", `^[A-Z]{2}$`)
	}
	if utf8.RuneCountInString(string(plain.Line1)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "line1", 1)
	}
	if utf8.RuneCountInString(string(plain.PostalCode)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "postal_code", 1)
	}
	*j = Address(plain)
	return nil
}

type RecipientJson struct {
	// AccessPasskey corresponds to the JSON schema field "access_passkey".
	AccessPasskey *string `json:"access_passkey,omitempty,omitzero" yaml:"access_passkey,omitempty" mapstructure:"access_passkey,omitempty"`

	// Address corresponds to the JSON schema field "address".
	Address Address `json:"address" yaml:"address" mapstructure:"address"`

	// Email corresponds to the JSON schema field "email".
	Email string `json:"email" yaml:"email" mapstructure:"email"`

	// IsBusiness corresponds to the JSON schema field "is_business".
	IsBusiness bool `json:"is_business" yaml:"is_business" mapstructure:"is_business"`

	// Language corresponds to the JSON schema field "language".
	Language RecipientJsonLanguage `json:"language" yaml:"language" mapstructure:"language"`

	// LegalName corresponds to the JSON schema field "legal_name".
	LegalName string `json:"legal_name" yaml:"legal_name" mapstructure:"legal_name"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number" yaml:"number" mapstructure:"number"`

	// PaymentTermsDays corresponds to the JSON schema field "payment_terms_days".
	PaymentTermsDays int `json:"payment_terms_days" yaml:"payment_terms_days" mapstructure:"payment_terms_days"`

	// TaxId corresponds to the JSON schema field "tax_id".
	TaxId *string `json:"tax_id,omitempty,omitzero" yaml:"tax_id,omitempty" mapstructure:"tax_id,omitempty"`

	// This client's client ID in the time-tracking tool (currently Toggl), if tracked
	// there at all — a Toggl client can span multiple Toggl projects, all grouped
	// under this one ID. Links an issued invoice for this recipient to that client's
	// tracked/predicted hours in the finance tracker — see internal/finance.
	TrackingClientId *int `json:"tracking_client_id,omitempty,omitzero" yaml:"tracking_client_id,omitempty" mapstructure:"tracking_client_id,omitempty"`

	// VatId corresponds to the JSON schema field "vat_id".
	VatId *string `json:"vat_id,omitempty,omitzero" yaml:"vat_id,omitempty" mapstructure:"vat_id,omitempty"`
}

type RecipientJsonLanguage string

const RecipientJsonLanguageBg RecipientJsonLanguage = "bg"
const RecipientJsonLanguageDe RecipientJsonLanguage = "de"
const RecipientJsonLanguageEn RecipientJsonLanguage = "en"
const RecipientJsonLanguageFr RecipientJsonLanguage = "fr"

var enumValues_RecipientJsonLanguage = []interface{}{
	"de",
	"en",
	"fr",
	"bg",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RecipientJsonLanguage) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RecipientJsonLanguage {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RecipientJsonLanguage, v)
	}
	*j = RecipientJsonLanguage(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RecipientJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["address"]; raw != nil && !ok {
		return fmt.Errorf("field address in RecipientJson: required")
	}
	if _, ok := raw["email"]; raw != nil && !ok {
		return fmt.Errorf("field email in RecipientJson: required")
	}
	if _, ok := raw["is_business"]; raw != nil && !ok {
		return fmt.Errorf("field is_business in RecipientJson: required")
	}
	if _, ok := raw["language"]; raw != nil && !ok {
		return fmt.Errorf("field language in RecipientJson: required")
	}
	if _, ok := raw["legal_name"]; raw != nil && !ok {
		return fmt.Errorf("field legal_name in RecipientJson: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in RecipientJson: required")
	}
	if _, ok := raw["payment_terms_days"]; raw != nil && !ok {
		return fmt.Errorf("field payment_terms_days in RecipientJson: required")
	}
	type Plain RecipientJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.AccessPasskey != nil && utf8.RuneCountInString(string(*plain.AccessPasskey)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "access_passkey", 1)
	}
	if utf8.RuneCountInString(string(plain.LegalName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "legal_name", 1)
	}
	if 1 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 1)
	}
	if 0 > plain.PaymentTermsDays {
		return fmt.Errorf("field %s: must be >= %v", "payment_terms_days", 0)
	}
	*j = RecipientJson(plain)
	return nil
}
